source 'https://rubygems.org'

gem 'capybara',                 '2.14.1'
gem 'cucumber',                 '2.4.0'
gem 'poltergeist'
gem 'pry', '0.10.4'
gem 'rspec', '3.6.0'
gem 'selenium-webdriver', '3.4.0'
